name: James Brooks' Blog
description: Personal Blog for James Brooks
url: http://kerspoon.com
title: kerspoon
exclude:   ["README.md", "Gemfile", "Gemfile.lock"]
permalink: /:categories/:year/:title/

assets:
  compress:
    css:  sass
    js:   uglifier
